{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-version-manager.fullname" . }}
  labels:
    {{- include "helm-version-manager.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-version-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "helm-version-manager.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
